site_name: Locksy Documentation
site_url: https://docs.synthesizedev.org
theme:
  name: material
  logo: assets/synthesize.png
  favicon: assets/synthesize.png
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark Mode

    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light Mode

markdown_extensions:
  - attr_list
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences