site_name: Locksy Documentation
site_url: https://docs.synthesizedev.org
theme:
  name: material
  logo: assets/synthesize.png
  favicon: assets/synthesize.png
  features:
    - navigation.footer
    - content.footnote.tooltips
    - content.tabs.link
    - toc.integrate
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark Mode

    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light Mode
  
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/6PbefPhxme
    - icon: fontawesome/solid/globe
      link: https://synthesizedev.org

markdown_extensions:
  - attr_list
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - md_in_html
  - pymdownx.blocks.caption
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      title: On this page
      toc_depth: 1-3

nav:
  - Home: index.md
  - Locksy:
    - Overview: locksy.md
    - Discord Commands: locksy-discord.md
    - Roblox Module: locksy-roblox.md