site_name: Locksy Documentation
site_url: https://docs.synthesizedev.org
theme:
  name: material
  logo: assets/synthesize.png
  favicon: assets/synthesize.png
  features:
    - navigation.footer
    - content.footnote.tooltips
    - content.tabs.link
  extra:
    social:
      - icon: simple/youtube
        link: https://youtube.com/@james-willett
      - icon: simple/linkedin
        link: https://linkedin.com/in/willettjames
  copyright: Copyright &copy; 2025 Synthesize
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark Mode

    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light Mode
  

markdown_extensions:
  - attr_list
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - md_in_html
  - pymdownx.blocks.caption
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Locksy:
    - Overview: locksy.md
    - Discord Commands: locksy-discord.md
    - Roblox Module: locksy-roblox.md